### ISSUE TITLE
pbss does not support in zktrie

### ISSUE THREAD

**Issue by hdiass** [kroma-network/kroma-up#36]
### Issue type

Bug

### OS platform and distribution

Docker

### Current behavior?

```
CRIT [04-19|12:35:51.422] pbss does not support in zktrie
```
Facing this error on geth  when trying to update to new release geth v0.5.1+ kroma-node v1.4.1

### Expected Behavior?

Node should boot normally 

### Standalone code or description to reproduce the issue

Update from previous version to this.

**Comment by hdiass** [comment]
@0xHansLee Help plz

**Comment by Pangssu** [comment]
Can you explain how you started the node? It would be helpful to know the command you entered.

**Comment by hdiass** [comment]
```
exec geth \
        --gcmode=archive \
        --trace.mptwitness=1  \
        --circuitparams.maxtxs=0  \
        --gpo.maxprice=100000000  \
        --bootnodes="enode://acf4af39e9d9f3bbdb700315fde6e909efc714bd9a012b0f6943c4f9110008e3da2cb6c2ac9d3b6d98184a5ead57c4409be4ae7b19da1f554ceee7ba86c1fc2e@p2p-0.kroma.network:30304?discport=30303,enode://a3b6a7087b3399eefdb1ce5870aa0e58a60bfeccf3f7f7c02f5e142b1a544d19c171f7688d08db786d5e9b3ba734482bf8cf29dab7d46917b9da7f61656fde39@p2p-1.kroma.network:30304?discport=30303"  \
        --networkid=255  \
        --ws  \
        --ws.port=8546 \
        --ws.addr=0.0.0.0 \
        --ws.origins=* \
        --ws.api="debug,eth,txpool,net,engine,kroma" \
        --http \
        --http.port=8545 \
        --http.addr=0.0.0.0 \
        --http.api="web3,debug,eth,txpool,net,engine,kroma" \
        --http.vhosts=* \
        --http.corsdomain=* \
        --authrpc.addr=localhost \
        --authrpc.jwtsecret=/node/jwt.txt \
        --authrpc.port=8551 \
        --authrpc.vhosts=* \
        --datadir=/database \
        --metrics \
        --metrics.addr=0.0.0.0 \
        --verbosity=3 \
        --syncmode=full \
        --snapshot=false \
        --rpc.batch-response-max-size=70000000 \
        --rpc.txfeecap=0 \
        --nat=extip:$EXTERNAL_IP \
        --miner.recommit=100ms \
        --port=$EXTERNAL_PORT_0
  ```

**Comment by hdiass** [comment]
@Pangssu Do you see anything wrong in my command ? i think this is related with state scheme but i don't see anything that required change related with this in the last commits of this repo. Used the last snapshot to bootstrap the node btw.

**Comment by hdiass** [comment]
So issue was actually on `geth --verbosity="3" init --datadir="/database" "/genesis.json"` that happened

**Comment by hdiass** [comment]
Commented that bit and looks like it works

**Comment by Pangssu** [comment]
Like [this](https://github.com/kroma-network/kroma-up/issues/37#issuecomment-2066698486) comment, I would recommend using version 1.3.4 for now.

**Comment by 0xHansLee** [comment]
I will close this issue for now. If you have any issues remaining, please re-open this issue with a comment.
