### ISSUE TITLE
Which version should we be in ?

### ISSUE THREAD

**Issue by hdiass** [kroma-network/kroma-up#37]
### Issue type

Support

### Current behavior?

Following this message on kroma discord #mainnet-announcements, what version should we be in: 
```
[Planned Upgrade Delay Announcement]

We want to inform you that due to an unexpected error encountered in version v1.4.1, we must postpone the upcoming upgrade. Currently, our team is investigating the exact cause and seeking mitigation strategies. We understand the importance of this upgrade and are working diligently to resolve the issue as quickly as possible.

We do not have a new upgrade date at this time, but we will keep you updated with the latest developments. We appreciate your understanding and patience during this process. Please stay tuned for further announcements regarding the new upgrade schedule.

Thank you for your continued support.
```

### Expected Behavior?

Clear instructions and stable releases..

### Standalone code or description to reproduce the issue

Don't know in which version i should leave my nodes running on.

**Comment by seolaoh** [comment]
Sorry about your inconvenience. You can use [v1.3.4](https://github.com/kroma-network/kroma-up/tree/v1.3.4), which was already on the Kroma mainnet.

**Comment by timweri** [comment]
@seolaoh Could we have an explicit comms on some official channel (Discord, Github release notes) to say that nodes on v1.4.1 should be downgraded to v1.3.4? The wording in the release notes only tells people to not use v1.4.1, but it is not very clear if we should rollback.

**Comment by seolaoh** [comment]
@timweri You can just downgrade your node to `v1.3.4`, no need to rollback. We'll comm the clear guide to official channels soon.
